solr:
  image:
   repository: solr
   tag: 7.4
  replicaCount: 1
  volumeClaimTemplates:
    storageSize: 5Gi

zookeeper:
  replicaCount: 1
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi

mysql:
  enabled: true
  # use fcrepo here; the web app can create it's own db with db:create
  mysqlDatabase: fcrepo
  mysqlPassword: CHANGEME
  mysqlRootPassword: CHANGEME
  mysqlUser: essi
  initializationFiles: {
    grant.sql: GRANT ALL PRIVILEGES ON * . * TO 'essi'@'%';
  }
  persistence:
    enabled: true
    size: 5Gi

redis:
  enabled: true
  usePassword: false
  master:
    persistence:
      enabled: true
      size: 1Gi

cantaloupe:
  image: 
    repository: iublibtech/cantaloupe
    tag: latest
  storage:
    size: 1Gi

fcrepo:
  image:
    repository: ualbertalib/docker-fcrepo4
    tag: 4.7
  storage:
    size: 5Gi

web:
  replicas: 2

sidekiq:
  replicas: 1
  timeout: 3600

rails:
  image:
    repository: registry.gitlab.com/notch8/essi
    tag: latest
  imagePullPolicy: Always
  imagePullSecrets:
    - name: gitlab
  shared:
    storage:
      size: 5Gi
      className: nfs

ingress:
  tlsSecretName: notch8-cloud-wildcard
  host: staging-essi-web.notch8.cloud
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  }

nameOverride:
  essi

env:
  configmap: 
    NAME: essi
    RAILS_LOG_TO_STDOUT: true
    FC_DATABASE_NAME: fcrepo
    MYSQL_USER: essi
    IN_DOCKER: "true"
    LD_LIBRARY_PATH: /opt/fits-latest/tools/mediainfo/linux
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
    MYSQL_DATABASE: essi_dev
    SOLR_CONFIGSET_SOURCE_PATH: solr/config
    SOLR_CONFIGSET: essi
    SOLR_CORE: essi

  secret:
    SECRET_KEY_BASE: CHANGEME
    MYSQL_PASSWORD: CHANGEME

  cantaloupe:
    configmap:
      HTTP_HTTP2_ENABLED: "true"
      HTTPS_HTTP2_ENABLED: "true"
      ENDPOINT_IIIF_CONTENT_DISPOSITION: none
      SOURCE_STATIC: HttpSource
      SOURCE_DELEGATE: "false"
      HTTPSOURCE_LOOKUP_STRATEGY: ScriptLookupStrategy
      DELEGATE_SCRIPT_ENABLED: "true"
      DELEGATE_SCRIPT_CACHE_ENABLED: "true"
      DELEGATE_SCRIPT_PATHNAME: /cantaloupe/delegate/delegates.rb
      FEDORA_PATH: /rest/dev
      PROCESSOR_SELECTION_STRATEGY: ManualSelectionStrategy
      PROCESSOR_MANUAL_SELECTIONSTRATEGY_JP2: OpenJpegProcessor
      CACHE_SERVER_DERIVATIVE_ENABLED: "true"
      CACHE_SERVER_INFO_ENABLED: "true"
      CACHE_SERVER_DERIVATIVE: HeapCache
      HEAPCACHE_TARGET_SIZE: 256M
      CACHE_SERVIER_DERIVATIVE_TTL_SECONDS: 0
      CACHE_SERVER_PURGE_MISSING: "true"
      LOG_APPLICATION_LEVEL: info
      LOG_ACCESS_CONSOLEAPPENDER_ENABLED: "true"

