image: registry.gitlab.com/notch8/scripts/builder:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - test

before_script:
  - export TAG=${CI_COMMIT_SHA:0:8}
  - export BRANCH=${CI_COMMIT_REF_NAME}
  - export REGISTRY_HOST=${CI_REGISTRY}
  - export REGISTRY_URI="/${CI_PROJECT_PATH}"
  - touch .env.development
  - touch .env.production

build:
  stage: build
  script:
    - docker info
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker-compose build --pull web
    - docker-compose push web

rspec:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  services:
    - name: redis:3
    - name: postgres
    - name: solr:7.7
      alias: solr
      entrypoint: ["docker-entrypoint.sh", "solr-precreate", "hydra-test", "/opt/config"]
    - name: botimer/fcrepo:4.5.1
      alias: fcrepo
  script:
    - cd /app
    - bundle exec rspec
  tags:
    - docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    GIT_STRATEGY: none
    RAILS_ENV: test
    DISABLE_DATABASE_ENVIRONMENT_CHECK: 1

