version: '3.7'
services:
  web:
    image: "${REGISTRY_HOST}${REGISTRY_URI}:${TAG}"
    command: bash -l -c "bundle exec puma -b tcp://0.0.0.0:3000"
    build:
      context: ./
      dockerfile: Dockerfile
      target: essi-dev
    environment:
      VIRTUAL_HOST: essi.docker
      VIRTUAL_PORT: 3000
      IN_DOCKER: 'true'
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    env_file:
      - .env.development
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - solr
      - fcrepo
      - db
      - minio
      - cantaloupe
      - worker
      - chrome

  debug:
    image: "${REGISTRY_HOST}${REGISTRY_URI}:${TAG}"
    command: tail -f /dev/null
    build:
      context: ./
      dockerfile: Dockerfile
      target: essi-dev
    environment:
      VIRTUAL_HOST: essi.docker
      VIRTUAL_PORT: 3000
      IN_DOCKER: 'true'
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true
    env_file:
      - .env.development
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - solr
      - fcrepo
      - db
      - minio
      - cantaloupe
      - worker
      - chrome

  worker:
    image: "${REGISTRY_HOST}${REGISTRY_URI}:${TAG}"
    command: bundle exec sidekiq 
    build:
      context: ./
      dockerfile: Dockerfile
      target: essi-dev
    environment:
      IN_DOCKER: 'true'
    stdin_open: true
    tty: true
    env_file:
      - .env.development
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - solr
      - fcrepo
      - db
      - minio

  db:
    image: mysql:5.7
    ports:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: essi
      MYSQL_DATABASE: essi_dev
      MYSQL_USER: essi
      MYSQL_PASSWORD: essi

  minio:
    image: minio/minio:RELEASE.2020-03-14T02-21-58Z
    ports:
      - '9000'
    environment:
      MINIO_ACCESS_KEY: essi-minio
      MINIO_SECRET_KEY: Essi12345
    volumes:
      - minio:/data
      - './staged_files:/nasvol'
    command: gateway nas /data
    depends_on:
      - minio_mount

  minio_mount:
    image: alpine:3.11
    volumes:
      - minio:/data
    command: ln -s /nasvol /data/essi-dropbox; exit 0

  cantaloupe:
    image: iublibtech/cantaloupe
    ports:
      - '8182:8182'
    environment:
      HTTP_HTTP2_ENABLED: "true"
      HTTPS_HTTP2_ENABLED: "true"
      ENDPOINT_IIIF_CONTENT_DISPOSITION: none
      SOURCE_STATIC: HttpSource
      SOURCE_DELEGATE: "false"
      HTTPSOURCE_LOOKUP_STRATEGY: ScriptLookupStrategy
      DELEGATE_SCRIPT_ENABLED: "true"
      DELEGATE_SCRIPT_CACHE_ENABLED: "true"
      DELEGATE_SCRIPT_PATHNAME: /cantaloupe/delegate/delegates.rb
      FEDORA_BASE: http://fcrepo:8080
      FEDORA_PATH: /rest/dev
      PROCESSOR_SELECTION_STRATEGY: ManualSelectionStrategy
      PROCESSOR_MANUAL_SELECTIONSTRATEGY_JP2: OpenJpegProcessor
      CACHE_SERVER_DERIVATIVE_ENABLED: "true"
      CACHE_SERVER_INFO_ENABLED: "true"
      CACHE_SERVER_DERIVATIVE: HeapCache
      HEAPCACHE_TARGET_SIZE: 256M
      CACHE_SERVIER_DERIVATIVE_TTL_SECONDS: 0
      CACHE_SERVER_PURGE_MISSING: "true"
      LOG_APPLICATION_LEVEL: info
      LOG_ACCESS_CONSOLEAPPENDER_ENABLED: "true"
    volumes:
      - './cantaloupe:/cantaloupe/delegate'

  redis:
    image: redis:5
    ports:
      - '6379'
    volumes:
      - 'redis:/data'

  solr:
    image: solr:7.7
    ports:
      - "8983"
    volumes:
      - './solr/config:/opt/config:delegated'
      - solr:/opt/solr/server/solr/mycores
      - './solr/lib/solr-tokenizing_suggester-7.x.jar:/opt/solr/contrib/solr-tokenizing_suggester-7.x.jar'
    env_file:
      - .env.development
      - .env
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - "${SOLR_CORE}"
      - /opt/config

  fcrepo:
    image: samvera/fcrepo4:4.7.5
    volumes:
      - 'fcrepo:/opt/data'
    ports:
      - "8080"

  chrome:
    image: selenium/standalone-chrome:3.141

volumes:
  fcrepo:
  mysql:
  redis:
  solr:
  minio:
