version: '3.7'

x-app:
  &default-app
  image: "${REGISTRY_HOST}${REGISTRY_URI}:${TAG}"
  #    image: iublibtech/essi:master
  build:
    context: ./
    dockerfile: Dockerfile
    target: essi-dev
    args:
      USER_ID: ${USER_ID:-1000}
      GROUP_ID: ${GROUP_ID:-1000}
  environment:
    IN_DOCKER: 'true'
  stdin_open: true
  tty: true
  env_file:
    - .env.development
    - .env
  volumes:
    - .:/app:cached
    - rails_cache:/app/tmp/cache
    - ./config/essi_config.docker.yml:/run/secrets/essi_config.yml
  depends_on:
    - redis_jobs
    - solr
    - fcrepo
    - db
    - minio
    - cantaloupe
    - chrome

services:
  web:
    image: nginxinc/nginx-unprivileged:stable-alpine
    volumes:
      - ./essi-nginx.nginx:/etc/nginx/conf.d/essi-nginx.conf
      - ./tmp/certs:/etc/nginx/certs
    ports:
      - "3000:3000"
    depends_on:
      - essi
      - worker
      - derivatives

  essi:
    << : *default-app
    command: bash -l -c "bundle install && bundle exec rake db:migrate db:seed yarn:install && bundle exec rails s"
    environment:
      VIRTUAL_HOST: essi.docker
      VIRTUAL_PORT: 3000
      IN_DOCKER: 'true'
      HUB_URL: http://chrome:4444/wd/hub

  worker:
    << : *default-app
    command: bash -c "bundle install && bundle exec sidekiq -c 4"

  derivatives:
    <<: *default-app
    environment:
      IN_DOCKER: 'true'
      SIDEKIQ_QUEUES: imageproc,derivatives
    command: bash -l -c "bundle install && bundle exec sidekiq -c 4"

  db:
    image: mysql:8.0
    ports:
      - '3307:3306'
    volumes:
      - mysql:/var/lib/mysql
      - './db/50-mysql-create-db.sql:/docker-entrypoint-initdb.d/50-mysql-create-db.sql'
    environment:
      MYSQL_ROOT_PASSWORD: essi

  minio:
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: essi-minio
      MINIO_ROOT_PASSWORD: Essi12345
      MINIO_DEFAULT_BUCKETS: 'essi-dev,essi-test'
    volumes:
      - minio:/data

  cantaloupe:
    image: uclalibrary/cantaloupe:5.0.5-7
    ports:
      - '8182:8182'
    environment:
      CANTALOUPE_SOURCE_DELEGATE: "true"
      CANTALOUPE_S3SOURCE_LOOKUP_STRATEGY: ScriptLookupStrategy
      CANTALOUPE_S3SOURCE_ENDPOINT: http://minio:9000
      CANTALOUPE_S3SOURCE_REGION: us-east-1  # Set with custom endpoint to avoid lookup query
      CANTALOUPE_S3SOURCE_ACCESS_KEY_ID: essi-minio
      CANTALOUPE_S3SOURCE_SECRET_KEY: Essi12345
      CANTALOUPE_HTTPSOURCE_LOOKUP_STRATEGY: ScriptLookupStrategy
      CANTALOUPE_HTTPSOURCE_CHUNKING: "false"
      CANTALOUPE_DELEGATE_SCRIPT_ENABLED: "true"
      CANTALOUPE_DELEGATE_SCRIPT_CACHE_ENABLED: "true"
      CANTALOUPE_DELEGATE_SCRIPT_PATHNAME: /cantaloupe/delegate/delegates.rb
      CANTALOUPE_FEDORA_BASE: http://fcrepo:8080
      CANTALOUPE_FEDORA_PATH: /rest/dev
      CANTALOUPE_PROCESSOR_SELECTION_STRATEGY: ManualSelectionStrategy
      CANTALOUPE_MANUAL_PROCESSOR_JPG: TurboJpegProcessor
      CANTALOUPE_MANUAL_PROCESSOR_JP2: GrokProcessor
      CANTALOUPE_PROCESSOR_STREAM_RETRIEVAL_STRATEGY: StreamStrategy
      CANTALOUPE_PROCESSOR_FALLBACK_RETRIEVAL_STRATEGY: CacheStrategy
      CANTALOUPE_CACHE_SERVER_SOURCE_ENABLED: "true"
      CANTALOUPE_CACHE_SERVER_SOURCE: FilesystemCache
      CANTALOUPE_CACHE_SERVER_SOURCE_TTL_SECONDS: 2592000
      CANTALOUPE_CACHE_SERVER_WORKER_ENABLED: "true"
      CANTALOUPE_CACHE_SERVER_WORKER_INTERVAL: 3600
      CANTALOUPE_FILESYSTEMCACHE_PATHNAME: /var/cache/cantaloupe
      CANTALOUPE_CACHE_SERVER_DERIVATIVE_ENABLED: "true"
      CANTALOUPE_CACHE_SERVER_INFO_ENABLED: "true"
      CANTALOUPE_CACHE_SERVER_DERIVATIVE: RedisCache
      CANTALOUPE_REDISCACHE_HOST: redis_cache
      CANTALOUPE_REDISCACHE_PORT: 6379
      CANTALOUPE_REDISCACHE_SSL: "false"
      CANTALOUPE_REDISCACHE_PASSWORD: ""
      CANTALOUPE_REDISCACHE_DATABASE: 0
      CANTALOUPE_HEAPCACHE_TARGET_SIZE: 256M
      CANTALOUPE_CACHE_SERVER_DERIVATIVE_TTL_SECONDS: 2592000
      CANTALOUPE_CACHE_SERVER_PURGE_MISSING: "true"
      CANTALOUPE_LOG_APPLICATION_LEVEL: debug
      CANTALOUPE_LOG_ERROR_RESPONSES: "true"
      CANTALOUPE_LOG_ACCESS_CONSOLEAPPENDER_ENABLED: "true"
    volumes:
      - './cantaloupe:/cantaloupe/delegate'
    depends_on:
      - redis_cache
      - fcrepo

  redis_jobs:
    image: redis:6-alpine
    ports:
      - '6380:6379'
    volumes:
      - 'redis:/data'
    command: redis-server --appendonly yes --maxmemory-policy noeviction

  redis_cache:
    image: redis:6-alpine
    ports:
      - '6381:6379'
    command: redis-server --maxmemory-policy allkeys-lru --maxmemory 256mb

  solr:
    image: solr:6.6
    ports:
      - "8983:8983"
    volumes:
      - './solr:/myconfig:delegated'
      - solr:/opt/solr/server/solr/mycores
      - './solr/lib/tokenizing-suggest-v1.0.1.jar:/opt/solr/contrib/tokenizing-suggest-v1.0.1.jar'
      - './solr/50-precreate-cores.sh:/docker-entrypoint-initdb.d/50-precreate-cores.sh'
    entrypoint:
      - docker-entrypoint.sh
      - solr-foreground

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    volumes:
      - 'fcrepo:/data'
    ports:
      - "8984:8080"

  chrome:
    image: seleniarm/standalone-chromium:4.9.0
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2G
    environment:
      SE_SCREEN_WIDTH: 1920
      SE_SCREEN_HEIGHT: 1080
    ports:
      - "4444:4444"
      - "5959:5900"

volumes:
  fcrepo:
  mysql:
  redis:
  solr:
  rails_cache:
  minio:
