version: '3.7'
services:
  web:
    image: "${REGISTRY_HOST}${REGISTRY_URI}:${TAG}"
    command: bash -l -c "bundle exec puma -b tcp://0.0.0.0:3000"
    build:
      context: ./
      dockerfile: Dockerfile
      target: essi-dev
    environment:
      VIRTUAL_HOST: essi.docker
      VIRTUAL_PORT: 3000
      IN_DOCKER: 'true'
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    env_file:
      - .env.development
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - solr
      - fcrepo
      - db
      - minio
      - worker
      - chrome

  debug:
    image: "${REGISTRY_HOST}${REGISTRY_URI}:${TAG}"
    command: tail -f /dev/null
    build:
      context: ./
      dockerfile: Dockerfile
      target: essi-dev
    environment:
      VIRTUAL_HOST: essi.docker
      VIRTUAL_PORT: 3000
      IN_DOCKER: 'true'
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    env_file:
      - .env.development
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - solr
      - fcrepo
      - db
      - minio
      - worker
      - chrome

  worker:
    image: "${REGISTRY_HOST}${REGISTRY_URI}:${TAG}"
    command: bundle exec sidekiq 
    build:
      context: ./
      dockerfile: Dockerfile
      target: essi-dev
    environment:
      IN_DOCKER: 'true'
    stdin_open: true
    tty: true
    env_file:
      - .env.development
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - solr
      - fcrepo
      - db
      - minio

  db:
    image: mysql:5.7
    ports:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: essi
      MYSQL_DATABASE: essi_dev
      MYSQL_USER: essi
      MYSQL_PASSWORD: essi

  minio:
    image: minio/minio:RELEASE.2020-02-27T00-23-05Z
    ports:
      - '9000'
    environment:
      MINIO_ACCESS_KEY: essi-minio
      MINIO_SECRET_KEY: Essi12345
    volumes:
      - minio:/data
      - './staged_files:/nasvol'
    command: gateway nas /data
    depends_on:
      - minio_mount

  minio_mount:
    image: alpine:3.11
    volumes:
      - minio:/data
    command: ln -s /nasvol /data/essi-dropbox

#  cantaloupe:
#    image: uclalibrary/cantaloupe-ucla:4.1.4
#    ports:
#      - '8182'
#    environment:
#      CANTALOUPE_ENDPOINT_ADMIN_ENABLED: true
#      CANTALOUPE_DELEGATE_SCRIPT_ENABLED: true
#      CANTALOUPE_DELEGATE_SCRIPT_PATHNAME: /usr/local/cantaloupe/delegates.rb
#      CANTALOUPE_DELEGATE_SCRIPT_CACHE_ENABLED: false
#      CANTALOUPE_SOURCE_DELEGATE: false
#      DELEGATE_URL: https://raw.githubusercontent.com/UCLALibrary/cantaloupe-delegate/master/lib/delegates.rb

  redis:
    image: redis:5
    ports:
      - '6379'
    volumes:
      - 'redis:/data'

  solr:
    image: solr:7.7
    ports:
      - "8983"
    volumes:
      - './solr/config:/opt/config:delegated'
      - solr:/opt/solr/server/solr/mycores
      - './solr/lib/solr-tokenizing_suggester-7.x.jar:/opt/solr/contrib/solr-tokenizing_suggester-7.x.jar'
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - "${SOLR_CORE}"
      - /opt/config

  fcrepo:
    image: samvera/fcrepo4:4.7.5
    volumes:
      - 'fcrepo:/opt/data'
    ports:
      - "8080"

  chrome:
    image: selenium/standalone-chrome:3.141

volumes:
  fcrepo:
  mysql:
  redis:
  solr:
  minio:
