# file-based supplement to API results
---
- code: 'B-MEDIASCHOOL'
  label: 'Bloomington - The Media School'
  address: 'Franklin Hall'
  address2: '601 East Kirkwood Ave'
  city: 'Bloomington'
  state: 'IN'
  zip: '47405'
  phone: '812-855-9247'
  email: 'tmsarch@indiana.edu'
  url: 'https://mediaschool.indiana.edu/about/archive.html'
  urlHours: 'https://mediaschool.indiana.edu/about/facilities/index.html'
  latitude: '39.166887'
  longitude: '-86.526490'
  parking: 'https://parking.indiana.edu/'
  notes: ''
- code: 'B-BFCA'
  label: 'Bloomington - Black Film Center & Archive'
  address: 'Herman B Wells Library, Room 044'
  address2: '1320 East Tenth Street'
  city: 'Bloomington'
  state: 'IN'
  zip: '47405'
  phone: 812-855-6041
  email: bfca@indiana.edu
  url: https://bfca.indiana.edu/
  urlHours: https://bfca.indiana.edu/contact/index.html
  latitude: '39.17098'
  longitude: '-86.516189'
  parking: https://parking.indiana.edu/
  notes: '' 
- code: 'B-IUMAA'
  label: 'Bloomington - Indiana University Museum of Archaeology and Anthropology'
  address: '416 North Indiana Avenue'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47408'
  phone: 812-855-6873
  email: iumaa@indiana.edu
  url: https://iumaa.iu.edu/
  urlHours: 
  latitude: '39.1700233'
  longitude: '-86.528326'
  parking: https://iumaa.iu.edu/about/building-information.html
  notes: ''
- code: 'B-WYLIEHOUSE'
  label: 'Bloomington - Wylie House Museum'
  address: '317 East 2nd Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47401'
  phone: 812-855-6224
  email: libwylie@indiana.edu
  url: https://libraries.indiana.edu/wylie-house-museum
  urlHours: https://libraries.indiana.edu/wylie-house-museum
  latitude: '39.1616539'
  longitude: '-86.5326939'
  parking: https://libraries.indiana.edu/file/wylie-house-museum-parking-pdf
  notes: ''
- code: I-EITELJORG
  label: Indianapolis - Eiteljorg Museum of American Indians and Western Art
  address: 500 West Washington Street
  address2:
  city: Indianapolis
  state: IN
  zip: '46204'
  phone: 317-636-9378
  email:
  url: https://eiteljorg.org/
  urlHours: https://eiteljorg.org/visit/map-hours-parking/
  latitude: '39.76872'
  longitude: "-86.16780"
  parking: https://eiteljorg.org/visit/map-hours-parking/
  notes:
- code: 'B-IGWS'
  label: 'Bloomington - Indiana Geological and Water Survey'
  address: 'Geology Building'
  address2: '1001 E. 10th St.'
  city: 'Bloomington'
  state: 'IN'
  zip: '47405'
  phone: '812-855-7636'
  email: 'igwsinfo@indiana.edu'
  url: 'https://igws.indiana.edu'
  urlHours: 'https://igws.indiana.edu/about/' 
  latitude: '39.1719'
  longitude: '-86.521264'
  parking: https://parking.indiana.edu/ 
  notes: ''
- code: 'B-ESAAD'
  label: 'Bloomington - Eskenazi School of Art, Architecture + Design'
  address: 'Fine Arts Building'
  address2: '1201 E. Seventh Street'
  city: 'Bloomington'
  state: 'IN'
  zip: '47405'
  phone: '812-855-4627'
  email: 'ksrichar@iu.edu'
  url: 'https://eskenazi.indiana.edu/exhibitions/sage-collection/index.html'
  urlHours: 'https://eskenazi.indiana.edu/exhibitions/sage-collection/index.html'
  latitude: '39.1689179'
  longitude: '-86.5189909'
  parking: https://parking.indiana.edu/
  notes: ''
