# file-based supplement to API results
---
- code: 'B-MEDIASCHOOL'
  label: 'Bloomington - The Media School'
  address: 'Franklin Hall'
  address2: '601 East Kirkwood Ave'
  city: 'Bloomington'
  state: 'IN'
  zip: '47405'
  phone: '812-855-9247'
  email: 'tmsarch@indiana.edu'
  url: 'https://mediaschool.indiana.edu/about/archive.html'
  urlHours: 'https://mediaschool.indiana.edu/about/facilities/index.html'
  latitude: '39.166887'
  longitude: '-86.526490'
  parking: 'https://parking.indiana.edu/'
  notes: ''
- code: 'B-BFCA'
  label: 'Bloomington - Black Film Center & Archive'
  address: 'Herman B Wells Library, Room 044'
  address2: '1320 East Tenth Street'
  city: 'Bloomington'
  state: 'IN'
  zip: '47405'
  phone: 812-855-6041
  email: bfca@indiana.edu
  url: https://bfca.indiana.edu/
  urlHours: https://bfca.indiana.edu/contact/index.html
  latitude: '39.17098'
  longitude: '-86.516189'
  parking: https://parking.indiana.edu/
  notes: '' 
- code: 'B-IUMAA'
  label: 'Bloomington - Indiana University Museum of Archaeology and Anthropology'
  address: '416 North Indiana Avenue'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47408'
  phone: 812-855-6873
  email: iumaa@indiana.edu
  url: https://iumaa.iu.edu/
  urlHours: 
  latitude: '39.1700233'
  longitude: '-86.528326'
  parking: https://iumaa.iu.edu/about/building-information.html
  notes: ''
- code: 'B-WYLIEHOUSE'
  label: 'Bloomington - Wylie House Museum'
  address: '317 East 2nd Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47401'
  phone: 812-855-6224
  email: libwylie@indiana.edu
  url: https://libraries.indiana.edu/wylie-house-museum
  urlHours: https://libraries.indiana.edu/wylie-house-museum
  latitude: '39.1616539'
  longitude: '-86.5326939'
  parking: https://libraries.indiana.edu/file/wylie-house-museum-parking-pdf
  notes: ''
