default: &default
  adapter: async
  url: redis://<%= Catorax.config[:redis][:host] %>:<%= Catorax.config[:redis][:port] %>/1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  adapter: redis
  channel_prefix: <%= Catorax.config[:redis][:namespace] %>
