default: &default
  adapter: async
  url: redis://<%= ESSI.config[:redis][:host] %>:<%= ESSI.config[:redis][:port] %>/1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  adapter: redis
  channel_prefix: <%= ESSI.config[:redis][:namespace] %>
