default: &default
  user: <%= Catorax.config[:fedora][:user] %>
  password: <%= Catorax.config[:fedora][:password] %>
  url: <%= Catorax.config[:fedora][:url] %>
  base_path: <%= Catorax.config[:fedora][:base_path] %>
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default

