default: &default
  user: <%= ESSI.config[:fedora][:user] %>
  password: <%= ESSI.config[:fedora][:password] %>
  url: <%= ESSI.config[:fedora][:url] %>
  base_path: <%= ESSI.config[:fedora][:base_path] %>
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default

