:enabled: true
:host: ads.example.edu
:tree: dc=ads,dc=example,dc=edu
:account_ou: Accounts
:group_ou: Groups
:auth:
  :method: :simple
  :username: cn=user,ou=Groups,ou=Accounts,dc=ads,dc=example,dc=edu
  :password: "password"

