#-------------------
# Other Schema Files
#-------------------
# This section specifies other configuration files that contain
# metadata information. Files are loaded in order, and the 
# directives in this file are loaded last. 
# File paths are specified relative to the application's 'config' directory. 
# Schema information from all files are merged together. Some options
# may be overridden in files loaded later. 
# Other options must be defined only once per property
# and cannot be overwritten. These include "predicate" and "definition". 

schema_files:
  - shared_schema.yml



#-------------------
# Property Settings
#-------------------
# This section defines every metadata property that can be used 
# in the system. Individual work types may override some settings 
# defined here. Predicates for each property should be defined
# here, and cannot be overridden once defined.

properties:

  default:
    definition: "This property has not yet been documented."
    required: false
    multiple: true
    primary: false
    hidden: false
    work_title: false
    input: scalar
    range: RDF:Literal

  resource_type:
    definition: "Type of resource?"
    required: false
    multiple: true
    primary: false
    hidden: true
    work_title: false
    predicate: "DC:type"

  title:
    definition: "The title of the resource."
    usage_note: "Multiple titles are allowed, but discouraged. In some contexts it cannot be predicted which title will be displayed."
    predicate: "DC:title"
    label: "Title"
    range: "rdfs:Literal"
    required: true
    primary: true
    work_title: true

  creator:
    definition: "A person or organization responsible for creating the resource."
    usage_note: "We plan to use a controlled vocabulary for this field in the future. It is encouraged to use names corresponding exactly to names from the LCSH names directory."
    predicate: "DC:creator"
    primary: true
    required: true
    facet: true

  contributor:
    definition: "A person or organization responsible for making contributions to the resource."
    usage_note: "We plan to use a controlled vocabulary for this field in the future. It is encouraged to use names corresponding exactly to names from the LCSH names directory."
    predicate: "DC:contributor"
    facet: true

  publisher:
    definition: "An entity responsible for making the resource available."
    usage_note: "We plan to use a controlled vocabulary for this field in the future. It is encouraged to use names corresponding exactly to names from the LCSH names directory."
    predicate: "DC:publisher"
    facet: true

  description:
    definition: "A summary or account of the resource."
    predicate: "DC:description"
    range: "rdfs:Literal"
    primary: true

  subject:
    definition: "The topic of the resource."
    usage_note: "We plan to use a controlled vocabulary for this field in the future. It is encouraged to use names corresponding exactly to names from the LCSH vocabulary."
    predicate: "DC:subject"
    facet: true
    primary: true

  date_created: 
    definition: "Date of creation of the resource."
    predicate: "DC:created"
    range: "edm:TimeSpan"
    label: "Date Created"
    primary: true
    required: true

  language:
    definition: "A language of the resource."
    predicate: "DC:language"
    range: skos:concept

  source:
    definition: "Use to record and previous publication information, e.g., the place of publication and publisher name for a physical resource."
    predicate: "DC:source"

  call_number:
    definition: "A call number identifier for the resource."
    predicate: "Bibframe:classification"
    multiple: false

  copyright_statement:
    definition: "Information about rights held in and over the resource."
    predicate: "DC:rights"
    primary: true
    required: true

  scale:
    label: "Scale"
    definition: "Ratio of the dimensions of a form contained or embodied in a resource to the dimensions of the entity it represents, e.g., for images or cartographic resources."
    usage_note: "Use this for scales of maps, aerial photos, and/or scanned documents. "
    
    predicate: "Bibframe:cartographicScale"
    range: "rdfs:Literal"

  date_published:
    definition: "Date of formal issuance (e.g., publication) of the resource."
    predicate: "DC:issued"
    range: "edm:TimeSpan"
    label: "Date Published"

    date_created:
      required: false

#-------------------
# Work Type Settings
#-------------------
# Here we define metadata settings based on work type.
# This section specifies which properties (defined above)
# may be applied to each work type, and may specify display
# settings such as "required" or "hidden".
# 
# In the future, this may be extended to actually define 
# the work types for the application here.


work_types:
  generic_work:
    properties:
      title:
      description:
        primary: true
        required: true
      creator:
        primary: true
        required: true
      contributor:
        primary: true
      rights_license:
        primary: true
  scientific:
    properties:
      title:
        label: "Scientific title"
      description:
        primary: true
        required: true
  image:
    properties:
      title:
      description:
        primary: true
        required: true
  paged_resource:
    properties:
      title:
      description:
        primary: true
        required: true
  bib_record:
    properties:
      title:
      description:
        primary: true
        required: true
      creator:
        primary: true
        required: true
      publisher:
        primary: true
      date_published:
        primary: true
      scale:
        primary: true
      contributor:
        primary: true
      rights_license:
        primary: true
