name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: iublibtech/essi
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
        buildargs: SOURCE_COMMIT
        tags: "latest,main"
      env: 
        SOURCE_COMMIT: ${{ github.sha }}
